image: ubuntu:16.04

# Caching so the next build will be fast too.
cache:
  paths:
  - ~/.stack
  - /builds/impresshs/javawlp/.stack-work
  # Z3 and Stack installation
  - /usr

before_script:
  # Install Stack and Z3 if they aren't already.
  - source ci-install.sh

build:
  script:
    - stack build --no-terminal --allow-different-user

test:
  script:
    - stack test --no-terminal --allow-different-user
