image: ubuntu:16.04

# Caching so the next build will be fast too.
cache:
  paths:
  - ~/.stack
  - /builds/impresshs/javawlp/.stack-work
  # Z3 and Stack installation
  - /usr

before_script:
  - which stack
  # Install Stack and Z3 if they aren't already.
  - if [ -z "$(which stack)" ]; then                  \
      apt-get update >/dev/null                    && \
      apt-get install curl -y >/dev/null           && \
      curl -sSL https://get.haskellstack.org/ | sh && \
      curl -L https://github.com/Z3Prover/z3/releases/download/z3-4.6.0/z3-4.6.0-x64-ubuntu-16.04.zip -o z3.zip >/dev/null && \
      unzip z3.zip >/dev/null                      && \
      mv z3-4.6.0-x64-ubuntu-16.04 z3 >/dev/null   && \
      mv z3/bin/z3 /usr/bin >/dev/null             && \
      mv z3/include/* /usr/include >/dev/null      && \
      mv z3/bin/libz3.so /usr/lib >/dev/null       && \
      rm    z3.zip >/dev/null                      && \
      rm -r z3 >/dev/null                             \
    fi

build:
  script:
    - stack build --no-terminal --only-dependencies --allow-different-user

test:
  script:
    - stack test --no-terminal --allow-different-user
